import { IVehicle } from "../types/types";

export const vehicleMockData: IVehicle[] = [
  {
    id: "veh_001",
    title: "Toyota Hiace",
    brand: "Toyota",
    model: "Hiace",
    year: 2022,
    type: "Van",
    transmission: "Manual",
    fuelType: "Diesel",
    color: "White",
    seatingCapacity: 15,
    pricePerDay: 8500,
    available: false,
    pickupLocation: "Kathmandu, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "BA-12-PA-5678",
    insuranceValidTill: "2026-03-15",
    createdAt: "2025-01-10T09:30:00Z",
  },
  {
    id: "veh_002",
    title: "Honda Civic",
    brand: "Honda",
    model: "Civic",
    year: 2021,
    type: "Car",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Black",
    seatingCapacity: 5,
    pricePerDay: 5000,
    available: false,
    pickupLocation: "Kathmandu, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "BA-03-CHA-1234",
    insuranceValidTill: "2025-11-20",
    createdAt: "2025-02-18T11:20:00Z",
  },
  {
    id: "veh_003",
    title: "Mahindra Scorpio",
    brand: "Mahindra",
    model: "Scorpio",
    year: 2020,
    type: "SUV",
    transmission: "Manual",
    fuelType: "Diesel",
    color: "Silver",
    seatingCapacity: 7,
    pricePerDay: 6500,
    available: false,
    pickupLocation: "Gandaki, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "GA-01-AA-9999",
    insuranceValidTill: "2026-01-10",
    createdAt: "2024-12-05T14:30:00Z",
  },
  {
    id: "veh_004",
    title: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    year: 2023,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Blue",
    seatingCapacity: 5,
    pricePerDay: 7000,
    available: true,
    pickupLocation: "Pokhara, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "BA-05-PA-7777",
    insuranceValidTill: "2026-05-30",
    createdAt: "2025-03-22T10:15:00Z",
  },
  {
    id: "veh_005",
    title: "Suzuki Swift",
    brand: "Suzuki",
    model: "Swift",
    year: 2022,
    type: "Car",
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Red",
    seatingCapacity: 5,
    pricePerDay: 4500,
    available: false,
    pickupLocation: "Kaski, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "KA-01-PA-3333",
    insuranceValidTill: "2025-12-15",
    createdAt: "2025-04-08T13:40:00Z",
  },
  {
    id: "veh_006",
    title: "Toyota Fortuner",
    brand: "Toyota",
    model: "Fortuner",
    year: 2023,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "White",
    seatingCapacity: 7,
    pricePerDay: 12000,
    available: false,
    pickupLocation: "Kathmandu, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "BA-02-PA-4444",
    insuranceValidTill: "2026-08-20",
    createdAt: "2025-05-14T09:00:00Z",
  },
  {
    id: "veh_007",
    title: "Nissan Kicks",
    brand: "Nissan",
    model: "Kicks",
    year: 2021,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "Orange",
    seatingCapacity: 5,
    pricePerDay: 5500,
    available: false,
    pickupLocation: "Lumbini, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "LU-01-PA-2222",
    insuranceValidTill: "2025-10-30",
    createdAt: "2025-06-20T11:25:00Z",
  },
  {
    id: "veh_008",
    title: "Maruti Ertiga",
    brand: "Maruti",
    model: "Ertiga",
    year: 2020,
    type: "Car",
    transmission: "Manual",
    fuelType: "Petrol",
    color: "Grey",
    seatingCapacity: 7,
    pricePerDay: 6000,
    available: true,
    pickupLocation: "Kathmandu, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "BA-08-PA-5555",
    insuranceValidTill: "2026-02-28",
    createdAt: "2024-11-30T15:50:00Z",
  },
  {
    id: "veh_009",
    title: "KIA Seltos",
    brand: "KIA",
    model: "Seltos",
    year: 2022,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Petrol",
    color: "White",
    seatingCapacity: 5,
    pricePerDay: 8000,
    available: false,
    pickupLocation: "Pokhara, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "BA-11-PA-6666",
    insuranceValidTill: "2026-04-10",
    createdAt: "2025-07-05T08:30:00Z",
  },
  {
    id: "veh_010",
    title: "Ford Endeavour",
    brand: "Ford",
    model: "Endeavour",
    year: 2021,
    type: "SUV",
    transmission: "Automatic",
    fuelType: "Diesel",
    color: "Black",
    seatingCapacity: 7,
    pricePerDay: 13000,
    available: true,
    pickupLocation: "Kathmandu, Nepal",
    vehicleFrontPhoto: "/default.jpg",
    vehicleBackPhoto: "/default.jpg",
    vehicleInteriorPhoto: "/default.jpg",
    vehicleSidePhoto: "/default.jpg",
    bluebookImage: "/default.jpg",
    insuranceDocumentImage: "/default.jpg",
    registrationNumber: "BA-07-PA-8888",
    insuranceValidTill: "2026-06-15",
    createdAt: "2025-08-18T12:45:00Z",
  },
];
